 std_msgs/Header header

 uint8 sync
 uint8 hdrSize
 uint8 ID
 uint8 family
 uint16 datasize
 uint16 dataChecksum
 uint16 hdrCecksum


 uint8 version
 uint8 offsetOfData
 uint64 serial_number
 uint8 year
 uint8 month
 uint8 day
 uint8 hour
 uint8 minutes
 uint8 seconds
 uint16 microSeconds100
 uint16 nbBeams
 uint64 error
 uint64 status
 float64 sound_speed  # m/s
 float64 temperature  # celsius
 float64 pressure  # Bar
 float64 velBeam1  # velocity for each beam
 float64 velBeam2
 float64 velBeam3
 float64 velBeam4
 float64 distBeam1  # distances for each beam
 float64 distBeam2
 float64 distBeam3
 float64 distBeam4
 float64 fomBeam1  # FOM for each beam
 float64 fomBeam2
 float64 fomBeam3
 float64 fomBeam4
 float64 timeDiff1Beam1  # DT1 s
 float64 timeDiff1Beam2
 float64 timeDiff1Beam3
 float64 timeDiff1Beam4
 float64 timeDiff2Beam1  # DT2
 float64 timeDiff2Beam2
 float64 timeDiff2Beam3
 float64 timeDiff2Beam4
 float64 timeVelEstBeam1  # Duration of velocity estimate for each beam. [s ]
 float64 timeVelEstBeam2
 float64 timeVelEstBeam3
 float64 timeVelEstBeam4
 float64 velX
 float64 velY
 float64 velZ1
 float64 velZ2
 float64 fomX
 float64 fomY
 float64 fomZ1
 float64 fomZ2
 float64 timeDiff1X
 float64 timeDiff1Y
 float64 timeDiff1Z1
 float64 timeDiff1Z2
 float64 timeDiff2X
 float64 timeDiff2Y
 float64 timeDiff2Z1
 float64 timeDiff2Z2
 float64 timeVelEstX
 float64 timeVelEstY
 float64 timeVelEstZ1
 float64 timeVelEstZ2
