uint8 HYDROPHONE=0
uint8 DICE=1
uint8 SONAR=2

uint8 HYDROPHONE_20=20
uint8 HYDROPHONE_21=21
uint8 HYDROPHONE_22=22
uint8 HYDROPHONE_23=23
uint8 HYDROPHONE_24=24
uint8 HYDROPHONE_25=25
uint8 HYDROPHONE_26=26
uint8 HYDROPHONE_27=27
uint8 HYDROPHONE_28=28
uint8 HYDROPHONE_29=29
uint8 HYDROPHONE_30=30
uint8 HYDROPHONE_31=31
uint8 HYDROPHONE_32=32
uint8 HYDROPHONE_33=33
uint8 HYDROPHONE_34=34
uint8 HYDROPHONE_35=35
uint8 HYDROPHONE_36=36
uint8 HYDROPHONE_37=37
uint8 HYDROPHONE_38=38
uint8 HYDROPHONE_39=39
uint8 HYDROPHONE_40=40


uint8 DICE_1=1
uint8 DICE_2=2
uint8 DICE_3=3
uint8 DICE_4=4
uint8 DICE_5=5
uint8 DICE_6=6

uint8 objective
uint8 sub_objective

---

geometry_msgs/Point position